### ISSUE TITLE
Steam Market bugged inventory overlay when choosing an item to sell

### ISSUE THREAD

**Issue by Bluellama9k** [purogamer/Fluent-for-Steam#52]
Its off center and im unable to scroll. It works in the metro skin btw
![steam_QNViRUzBDU](https://user-images.githubusercontent.com/94748723/171624003-b9769ad2-de86-4e48-951c-fc3f31325cb8.png)

**Comment by redsigma** [comment]
Try open resource/webkit.css and paste this at the bottom

It's taken from the metroskin. Also i wonder if the default steam has this problem. Last time i checked it had

```css
/* Fix Activity Popups width */
.flat_page .modal_frame{
	width: 97% !important;
	left: 0px !important;

	margin: 0px 40px 0px 10px !important;
}
/* Fix Activity Popups not being scrollable */
#modalContentFrameContainer{
	height: 100% !important;
	overflow: scroll !important;
}
```
